import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";

import { api } from "@/utils/api";

export default function Home() {
  const { data: session, status } = useSession();

  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  const router = useRouter();

  return (
    <>
      <Head>
        <title>Chornia</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center justify-center ">
        <h1>{session?.user.email}</h1>
        <button
          onClick={() => {
            signOut();
          }}
        >
          Logout
        </button>
     
      </main>
    </>
  );
}
